# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acceuil.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(802, 585)
        Form.setMinimumSize(QtCore.QSize(802, 585))
        Form.setMaximumSize(QtCore.QSize(802, 585))
        Form.setStyleSheet("background-color: rgb(203, 203, 204);")
        self.lbl_Date = QtWidgets.QLabel(Form)
        self.lbl_Date.setGeometry(QtCore.QRect(480, 20, 291, 31))
        self.lbl_Date.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Date.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lbl_Date.setText("")
        self.lbl_Date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Date.setObjectName("lbl_Date")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 761, 61))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("font: 40pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);\n"
"\n"
"\n"
"\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.btn_Listes = QtWidgets.QPushButton(Form)
        self.btn_Listes.setGeometry(QtCore.QRect(520, 480, 221, 41))
        self.btn_Listes.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"font: 14pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.btn_Listes.setObjectName("btn_Listes")
        self.btn_NewDeclaration = QtWidgets.QPushButton(Form)
        self.btn_NewDeclaration.setGeometry(QtCore.QRect(70, 480, 231, 41))
        self.btn_NewDeclaration.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"font: 14pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.btn_NewDeclaration.setObjectName("btn_NewDeclaration")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(61, 190, 341, 23))
        self.label_2.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_2.setObjectName("label_2")
        self.lbl_NbreNaissancesJour = QtWidgets.QLabel(Form)
        self.lbl_NbreNaissancesJour.setGeometry(QtCore.QRect(500, 190, 251, 23))
        self.lbl_NbreNaissancesJour.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 255);")
        self.lbl_NbreNaissancesJour.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_NbreNaissancesJour.setObjectName("lbl_NbreNaissancesJour")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(63, 250, 321, 23))
        self.label_3.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_3.setObjectName("label_3")
        self.lbl_NbrNaissancesMois = QtWidgets.QLabel(Form)
        self.lbl_NbrNaissancesMois.setGeometry(QtCore.QRect(500, 240, 251, 23))
        self.lbl_NbrNaissancesMois.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 255);")
        self.lbl_NbrNaissancesMois.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_NbrNaissancesMois.setObjectName("lbl_NbrNaissancesMois")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(56, 320, 331, 23))
        self.label_4.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_4.setObjectName("label_4")
        self.lbl_NbrNaissancesYear = QtWidgets.QLabel(Form)
        self.lbl_NbrNaissancesYear.setGeometry(QtCore.QRect(500, 310, 251, 23))
        self.lbl_NbrNaissancesYear.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 255);")
        self.lbl_NbrNaissancesYear.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_NbrNaissancesYear.setObjectName("lbl_NbrNaissancesYear")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Bienvenue sur BabyID"))
        self.btn_Listes.setText(_translate("Form", "Consulter le registre"))
        self.btn_NewDeclaration.setText(_translate("Form", "Nouvelle déclaration"))
        self.label_2.setText(_translate("Form", "Nombre d\'enregistrements aujourd\'hui :"))
        self.lbl_NbreNaissancesJour.setText(_translate("Form", "Ce jour"))
        self.label_3.setText(_translate("Form", "Nombre d\'enregistrements ce mois :"))
        self.lbl_NbrNaissancesMois.setText(_translate("Form", "Ce mois"))
        self.label_4.setText(_translate("Form", "Nombre d\'enregistrements cette année :"))
        self.lbl_NbrNaissancesYear.setText(_translate("Form", "Cette annee"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
