# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 606)
        MainWindow.setMinimumSize(QtCore.QSize(802, 606))
        MainWindow.setMaximumSize(QtCore.QSize(802, 606))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(802, 585))
        self.centralwidget.setMaximumSize(QtCore.QSize(802, 585))
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 801, 581))
        self.stackedWidget.setStyleSheet("background-color: rgb(203, 203, 204);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_Acceuil = QtWidgets.QWidget()
        self.page_Acceuil.setObjectName("page_Acceuil")
        self.stackedWidget.addWidget(self.page_Acceuil)
        self.page_Saisie = QtWidgets.QWidget()
        self.page_Saisie.setObjectName("page_Saisie")
        self.stackedWidget.addWidget(self.page_Saisie)
        self.page_listes = QtWidgets.QWidget()
        self.page_listes.setObjectName("page_listes")
        self.stackedWidget.addWidget(self.page_listes)
        self.page_stats = QtWidgets.QWidget()
        self.page_stats.setObjectName("page_stats")
        self.stackedWidget.addWidget(self.page_stats)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 802, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuMenu = QtWidgets.QMenu(self.menuBar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAjouter = QtWidgets.QAction(MainWindow)
        self.actionAjouter.setObjectName("actionAjouter")
        self.actionModifier = QtWidgets.QAction(MainWindow)
        self.actionModifier.setObjectName("actionModifier")
        self.actionAcceuil = QtWidgets.QAction(MainWindow)
        self.actionAcceuil.setObjectName("actionAcceuil")
        self.actionEnregistrer_un_nouveau_N = QtWidgets.QAction(MainWindow)
        self.actionEnregistrer_un_nouveau_N.setObjectName("actionEnregistrer_un_nouveau_N")
        self.actionListes = QtWidgets.QAction(MainWindow)
        self.actionListes.setObjectName("actionListes")
        self.actionStatistiques = QtWidgets.QAction(MainWindow)
        self.actionStatistiques.setObjectName("actionStatistiques")
        self.menuMenu.addAction(self.actionAcceuil)
        self.menuMenu.addAction(self.actionEnregistrer_un_nouveau_N)
        self.menuMenu.addAction(self.actionListes)
        self.menuBar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BabyID "))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionAjouter.setText(_translate("MainWindow", "Ajouter"))
        self.actionModifier.setText(_translate("MainWindow", "Modifier"))
        self.actionAcceuil.setText(_translate("MainWindow", "Acceuil"))
        self.actionEnregistrer_un_nouveau_N.setText(_translate("MainWindow", "Enregistrer un nouveau Né"))
        self.actionListes.setText(_translate("MainWindow", "Listes"))
        self.actionStatistiques.setText(_translate("MainWindow", "Statistiques"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
