# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pageModifier.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(802, 585)
        Form.setMinimumSize(QtCore.QSize(802, 585))
        Form.setMaximumSize(QtCore.QSize(802, 585))
        Form.setStyleSheet("background-color: rgb(203, 203, 204);")
        self.lineEdit_PostNom = QtWidgets.QLineEdit(Form)
        self.lineEdit_PostNom.setGeometry(QtCore.QRect(253, 160, 441, 27))
        self.lineEdit_PostNom.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lineEdit_PostNom.setObjectName("lineEdit_PostNom")
        self.lineEdit_Nom_Mere = QtWidgets.QLineEdit(Form)
        self.lineEdit_Nom_Mere.setGeometry(QtCore.QRect(250, 480, 441, 27))
        self.lineEdit_Nom_Mere.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lineEdit_Nom_Mere.setObjectName("lineEdit_Nom_Mere")
        self.lineEdit_Prenom = QtWidgets.QLineEdit(Form)
        self.lineEdit_Prenom.setGeometry(QtCore.QRect(253, 200, 441, 27))
        self.lineEdit_Prenom.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lineEdit_Prenom.setObjectName("lineEdit_Prenom")
        self.cb_Sexe = QtWidgets.QComboBox(Form)
        self.cb_Sexe.setGeometry(QtCore.QRect(250, 240, 441, 27))
        self.cb_Sexe.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.cb_Sexe.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cb_Sexe.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"")
        self.cb_Sexe.setObjectName("cb_Sexe")
        self.cb_Sexe.addItem("")
        self.cb_Sexe.addItem("")
        self.btn_Modifier = QtWidgets.QPushButton(Form)
        self.btn_Modifier.setGeometry(QtCore.QRect(56, 550, 211, 31))
        self.btn_Modifier.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Modifier.setStyleSheet("background-color: rgb(11, 109, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Times New Roman\";")
        self.btn_Modifier.setDefault(False)
        self.btn_Modifier.setFlat(False)
        self.btn_Modifier.setObjectName("btn_Modifier")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(137, 161, 86, 21))
        self.label_3.setStyleSheet("font: 14pt \"Times New Roman\";")
        self.label_3.setObjectName("label_3")
        self.btn_Annuler = QtWidgets.QPushButton(Form)
        self.btn_Annuler.setGeometry(QtCore.QRect(490, 550, 201, 31))
        self.btn_Annuler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Annuler.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Times New Roman\";")
        self.btn_Annuler.setObjectName("btn_Annuler")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 120, 46, 21))
        self.label.setStyleSheet("font: 14pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(91, 481, 127, 21))
        self.label_9.setStyleSheet("font: 14pt \"Times New Roman\";")
        self.label_9.setObjectName("label_9")
        self.dateEdit = QtWidgets.QDateEdit(Form)
        self.dateEdit.setGeometry(QtCore.QRect(250, 280, 441, 25))
        self.dateEdit.setStyleSheet("font: 14pt \"Times New Roman\";\n")
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.doubleSpinBox_Poids = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_Poids.setGeometry(QtCore.QRect(250, 360, 441, 25))
        self.doubleSpinBox_Poids.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.doubleSpinBox_Poids.setObjectName("doubleSpinBox_Poids")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(170, 360, 52, 21))
        self.label_10.setStyleSheet("font: 14pt \"Times New Roman\";")
        self.label_10.setObjectName("label_10")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 771, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("font: 20pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(0, 0, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(157, 201, 73, 21))
        self.label_4.setStyleSheet("font: 14pt \"Times New Roman\";")
        self.label_4.setObjectName("label_4")
        self.lineEdit_Nom = QtWidgets.QLineEdit(Form)
        self.lineEdit_Nom.setGeometry(QtCore.QRect(253, 120, 441, 27))
        self.lineEdit_Nom.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lineEdit_Nom.setObjectName("lineEdit_Nom")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(90, 280, 142, 21))
        self.label_6.setStyleSheet("font: 14pt \"Times New Roman\";")
        self.label_6.setObjectName("label_6")
        self.lineEdit_Nom_Pere = QtWidgets.QLineEdit(Form)
        self.lineEdit_Nom_Pere.setGeometry(QtCore.QRect(250, 440, 441, 27))
        self.lineEdit_Nom_Pere.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lineEdit_Nom_Pere.setObjectName("lineEdit_Nom_Pere")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(81, 321, 140, 21))
        self.label_7.setStyleSheet("font: 14pt \"Times New Roman\";")
        self.label_7.setObjectName("label_7")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(120, 400, 110, 21))
        self.label_11.setStyleSheet("font: 14pt \"Times New Roman\";")
        self.label_11.setObjectName("label_11")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(180, 240, 45, 21))
        self.label_5.setStyleSheet("font: 14pt \"Times New Roman\";")
        self.label_5.setObjectName("label_5")
        self.doubleSpinBox_taille = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_taille.setGeometry(QtCore.QRect(250, 400, 441, 25))
        self.doubleSpinBox_taille.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.doubleSpinBox_taille.setObjectName("doubleSpinBox_taille")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(117, 441, 113, 21))
        self.label_8.setStyleSheet("font: 14pt \"Times New Roman\";")
        self.label_8.setObjectName("label_8")
        self.lineEdit_LieuNaissance = QtWidgets.QLineEdit(Form)
        self.lineEdit_LieuNaissance.setGeometry(QtCore.QRect(250, 320, 441, 27))
        self.lineEdit_LieuNaissance.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lineEdit_LieuNaissance.setObjectName("lineEdit_LieuNaissance")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(110, 80, 111, 21))
        self.label_13.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_13.setObjectName("label_13")
        self.lbl_ID = QtWidgets.QLabel(Form)
        self.lbl_ID.setGeometry(QtCore.QRect(250, 80, 441, 21))
        self.lbl_ID.setStyleSheet("font: 14pt \"Times New Roman\";")
        self.lbl_ID.setText("")
        self.lbl_ID.setObjectName("lbl_ID")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cb_Sexe.setItemText(0, _translate("Form", "Masculin"))
        self.cb_Sexe.setItemText(1, _translate("Form", "Feminin"))
        self.btn_Modifier.setText(_translate("Form", "Modifier"))
        self.label_3.setText(_translate("Form", "Post-Nom :"))
        self.btn_Annuler.setText(_translate("Form", "Annuler"))
        self.label.setText(_translate("Form", "Nom :"))
        self.label_9.setText(_translate("Form", "Nom de la mère :"))
        self.label_10.setText(_translate("Form", "Poids :"))
        self.label_2.setText(_translate("Form", "Modifier"))
        self.label_4.setText(_translate("Form", "Prenom :"))
        self.label_6.setText(_translate("Form", "Date de naissance :"))
        self.label_7.setText(_translate("Form", "Lieu de naissance :"))
        self.label_11.setText(_translate("Form", "Taille (en cm) :"))
        self.label_5.setText(_translate("Form", "Sexe :"))
        self.label_8.setText(_translate("Form", "Nom du père :"))
        self.label_13.setText(_translate("Form", "ID de l\'enfant :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
